---
kind: pipeline
name: redirect

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ruby:2.5
  commands:
  - ./build.sh ${DRONE_BUILD_NUMBER}

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - ./test.deps.sh
  - py.test --cov redirect

- name: test-integration
  image: syncloud/build-deps-amd64
  commands:
  - ./deploy.deps.sh
  - cd artifact
  - ../ci/deploy ${DRONE_BUILD_NUMBER} integration syncloud.test
  - cd ../integration
  - py.test -x -s verify.py --domain=syncloud.test
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=desktop --domain=syncloud.test
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=mobile --domain=syncloud.test
  volumes:
  - name: shm
    path: /dev/shm

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/redirect/${DRONE_BUILD_NUMBER}
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: statsd
  image: statsd/statsd

- name: mail
  image: mailhog/mailhog:v1.0.0
  environment:
    MH_API_BIND_ADDR: 0.0.0.0:80
    MH_AUTH_FILE: /drone/src/integration/mailhog.auth
    MH_HOSTNAME: syncloud.test
    MH_SMTP_BIND_ADDR: 0.0.0.0:25

- name: mysql
  image: mysql:5.7.30
  environment:
    MYSQL_ROOT_PASSWORD: root

volumes:
- name: shm
  temp: {}

...
