---
kind: pipeline
name: redirect

platform:
  os: linux
  arch: amd64

steps:
- name: build web
  image: node
  commands:
  - mkdir build
  - cd www
  - npm install
  - npm run test
  - npm run lint
  - npm run build
  - cp -r dist ../build/www

- name: build backend
  image: golang:1.15.6
  commands:
  - cd backend
  - go test ./... -cover
  - go build -o ../build/bin/redirect cmd/main.go

- name: package
  image: syncloud/build-deps-amd64
  commands:
  - cp -r bin build
  - cp -r redirect build
  - cp requirements.txt build
  - cp -r config build
  - cp -r db build
  - cp -r emails build
  - cp redirect_*.wsgi build
  - mkdir artifact
  - tar czf artifact/redirect-${DRONE_BUILD_NUMBER}.tar.gz -C build .

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - apt-get update -qq
  - apt-get install -y -qq mysql-client libmysqlclient-dev
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - adduser --disabled-password --gecos "" test
  - mkdir mail.root
  - chown test. mail.root
  - ./ci/recreatedb
  - py.test --cov redirect

- name: test-integration
  image: syncloud/build-deps-amd64
  commands:
  - pip install -r dev_requirements.txt
  - cd integration
  - py.test -x -vv -s verify.py --domain=syncloud.test --device-host=device --build-number=${DRONE_BUILD_NUMBER}
  environment:
    access_key_id:
      from_secret: access_key_id
    hosted_zone_id:
      from_secret: hosted_zone_id
    secret_access_key:
      from_secret: secret_access_key

- name: test-ui
  image: syncloud/build-deps-amd64
  commands:
  - pip install -r dev_requirements.txt
  - cd integration
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=desktop --domain=syncloud.test --device-host=device
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=mobile --domain=syncloud.test --device-host=device
  volumes:
  - name: shm
    path: /dev/shm

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/redirect/${DRONE_BUILD_NUMBER}
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: statsd
  image: statsd/statsd

- name: mail
  image: mailhog/mailhog:v1.0.0
  environment:
    MH_HOSTNAME: syncloud.test

- name: mysql
  image: mysql:5.7.30
  environment:
    MYSQL_ROOT_PASSWORD: root

- name: device
  image: syncloud/platform-jessie-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: shm
  temp: {}

...
