---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./test.deps.sh
  - ./configure test
  - ./ci/redirectdb create redirect
  - py.test --cov redirect

...
