---
kind: pipeline
name: redirect

platform:
  os: linux
  arch: amd64

steps:
- name: build web
  image: jekyll/jekyll:4.1.0
  commands:
  - mkdir build
  - cd www
  - mkdir .jekyll-cache _site
  - jekyll build
  - cp -r _site ../build/www

- name: build backend
  image: golang:1.14
  commands:
  - cd backend
  - go test ./... -cover
  - go build -o ../build/bin/backend cmd/main.go

- name: package
  image: syncloud/build-deps-amd64
  commands:
  - cp -r bin build
  - cp -r redirect build
  - cp requirements.txt build
  - cp -r config build
  - cp -r emails build
  - cp redirect_*.wsgi build
  - mkdir artifact
  - tar czf artifact/redirect-${DRONE_BUILD_NUMBER}.tar.gz -C build .

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - ./test.deps.sh
  - py.test --cov redirect

- name: test-integration
  image: syncloud/build-deps-amd64
  commands:
  - pip install -r dev_requirements.txt
  - cd integration
  - py.test -x -s verify.py --domain=syncloud.test --device-host=device --build-number=${DRONE_BUILD_NUMBER}

- name: test-ui
  image: syncloud/build-deps-amd64
  commands:
  - pip install -r dev_requirements.txt
  - cd integration
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=desktop --domain=syncloud.test --device-host=device
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=mobile --domain=syncloud.test --device-host=device
  volumes:
  - name: shm
    path: /dev/shm

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/redirect/${DRONE_BUILD_NUMBER}
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: statsd
  image: statsd/statsd

- name: mail
  image: mailhog/mailhog:v1.0.0
  environment:
    MH_HOSTNAME: syncloud.test

- name: mysql
  image: mysql:5.7.30
  environment:
    MYSQL_ROOT_PASSWORD: root

- name: device
  image: syncloud/platform-jessie-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: shm
  temp: {}

...
