---
kind: pipeline
name: redirect

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh ${DRONE_BUILD_NUMBER}

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - ./test.deps.sh
  - cp -rf config/test/* .
  - ./ci/redirectdb create redirect
  - py.test --cov redirect

- name: test-integration
  image: syncloud/build-deps-amd64
  commands:
  - ./deploy.deps.sh
  - cd artifact
  - ../ci/deploy ${DRONE_BUILD_NUMBER} uat syncloud.test
  - cd ../integration
  - py.test -x -s verify.py --domain=syncloud.test
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=desktop --domain=syncloud.test
  - xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=mobile --domain=syncloud.test
  volumes:
  - name: shm
    path: /dev/shm

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/redirect/${DRONE_BUILD_NUMBER}
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

volumes:
- name: shm
  temp: {}

...
