language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
before_script:
  - ./configure test
  - mysql < db/init.sql
script: py.test --cov redirect
