language: python
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
before_script:
  - mysql < db/init.sql
  - python redirect/webrest.py &
  - sleep 3
script: py.test --cov redirect
