map $ssl_preread_server_name $syncloud_upstream {
    www.__SYNCLOUD_DOMAIN__   apache_backend;
    __SYNCLOUD_DOMAIN__       apache_backend;
    api.__SYNCLOUD_DOMAIN__   apache_backend;
    ""                        frps_control;
    default                   frps_vhost;
}

upstream apache_backend {
    server 127.0.0.1:8443;
}

upstream frps_vhost {
    server 127.0.0.1:4443;
}

upstream frps_control {
    server 127.0.0.1:7000;
}

server {
    listen 443;
    listen [::]:443;
    ssl_preread on;
    proxy_timeout 1h;
    proxy_pass $syncloud_upstream;
}
