#!/usr/bin/env python
import ConfigParser
import os
from subprocess import check_output

config = ConfigParser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), '../redirect/config.cfg'))

host = config.get('mysql', 'host')
user = config.get('mysql', 'user')
passwd = config.get('mysql', 'passwd')

command = 'mysqldump -h {0} -u {1} -p{2} --compact redirect > /home/redirect/redirect.backup'.format(host, user, passwd)

print check_output(command, shell=True)