#!/bin/bash -e

if [[ -z "$2" ]]; then
    echo "usage $0 version env"
    exit 1
fi

VERSION=$1
ENV=$2

TARGET=/var/www/redirect/${VERSION}
CURRENT=/var/www/redirect/current

mkdir -p ${TARGET}
tar xf redirect-${VERSION}.tar.gz -C ${TARGET}
rm -f ${CURRENT}
ln -s ${TARGET} ${CURRENT}
sudo pip install -r ${CURRENT}/requirements.txt
cp -rf ${CURRENT}/config/${ENV}/* ${CURRENT}
sudo service apache2 restart
