#!/bin/bash -e

if [[ -z "$3" ]]; then
    echo "usage $0 version env domain"
    exit 1
fi

VERSION=$1
ENV=$2
SYNCLOUD_DOMAIN=$3

TARGET=/var/www/redirect/${VERSION}
CURRENT=/var/www/redirect/current

mkdir -p ${TARGET}
tar xf redirect-${VERSION}.tar.gz -C ${TARGET}
rm -f ${CURRENT}
ln -s ${TARGET} ${CURRENT}
sudo pip install -r ${CURRENT}/requirements.txt
cp -rf ${CURRENT}/config/${ENV}/* ${CURRENT}
cp ${CURRENT}/apache/redirect.conf /etc/apache2/sites-available
if  ! id -u redirect > /dev/null 2>&1; then
    sudo adduser --disabled-password --gecos "" redirect
fi
sudo chown -R redirect. ${CURRENT}
if a2query -s 000-default; then
  sudo a2dissite 000-default
fi
if ! a2query -s redirect; then
  sudo a2ensite redirect
fi
a2enmod rewrite
a2enmod ssl
sed -i '/SYNCLOUD_DOMAIN.*/d' /etc/apache2/envvars
echo "export SYNCLOUD_DOMAIN=${SYNCLOUD_DOMAIN}" >> /etc/apache2/envvars
sudo service apache2 restart
