#!/bin/bash -e

if [[ -z "$3" ]]; then
    echo "usage $0 version env domain"
    exit 1
fi

VERSION=$1
ENV=$2
SYNCLOUD_DOMAIN=$3

REDIRECT_DIR=/var/www/redirect
TARGET=${REDIRECT_DIR}/${VERSION}
CURRENT=${REDIRECT_DIR}/current

mkdir -p ${TARGET}
tar xf redirect-${VERSION}.tar.gz -C ${TARGET}

if [[ -f ${CURRENT}/bin/uninstall.sh ]]; then
  ${CURRENT}/bin/uninstall.sh
fi

rm -f ${CURRENT}
ln -s ${TARGET} ${CURRENT}

${CURRENT}/bin/install.sh ${ENV} ${SYNCLOUD_DOMAIN}