#!/usr/bin/env python
from os.path import join, dirname
import sys
sys.path.append(join(dirname(__file__), '..'))
import ConfigParser
import os
from subprocess import check_output

script_base = os.path.join(os.path.dirname(__file__), '../db')

config = ConfigParser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), '../redirect/config.cfg'))
host = config.get('mysql', 'host')
user = config.get('mysql', 'user')
passwd = config.get('mysql', 'passwd')
db = 'redirect_test'


def upgrade(script):
    print check_output("mysql -h {0} -u {1} -p{2} {3} < {4}/{5}".format(
        host, user, passwd, db, script_base, script), shell=True)

upgrade('001_init_version.sql')
upgrade('002_tables.sql')
upgrade('003_migrate_users.sql')