#!/usr/bin/env python

from os.path import join, dirname
import sys
from ConfigParser import ConfigParser
from database import Runner


if __name__=='__main__':
    if len(sys.argv) < 3:
        sys.exit('Usage: %s <source database> <destination database>' % sys.argv[0])

    database = sys.argv[1]
    database_after = sys.argv[2]

    config = ConfigParser()
    config.read(join(dirname(__file__), '../redirect/config.cfg'))
    host = config.get('mysql', 'host')
    user = config.get('mysql', 'user')
    passwd = config.get('mysql', 'passwd')

    script_base = join(dirname(__file__), '../db')

    runner = Runner(host, user, passwd)
    runner.backup(database, '~/temp-redirect-backup')
    runner.restore('redirect_backup', '~/temp-redirect-backup')

    runner.drop(database_after)
    runner.create(database_after)
    runner.execute('set global foreign_key_checks=0;')
    runner.run(database_after, join(script_base, 'init.sql'))
    runner.run(database_after, join(script_base, '004.sql'))
    runner.execute('set global foreign_key_checks=1;')
