#!/bin/bash -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mysql --host=mysql --user=root --password=root -e "drop DATABASE if exists redirect"
mysql --host=mysql --user=root --password=root -e "CREATE DATABASE redirect"
for migration in ${DIR}/../backend/db/migrations/*.up.sql; do
  mysql --host=mysql --user=root --password=root redirect < "$migration"
done

