#!/usr/bin/env python
import ConfigParser
import os
from subprocess import check_output

config = ConfigParser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), '../redirect/config.cfg'))
host = config.get('mysql', 'host')
user = config.get('mysql', 'user')
passwd = config.get('mysql', 'passwd')


def mysql(query):
    print check_output("mysql -h {0} -u {1} -p{2} {3}".format(host, user, passwd, query), shell=True)

mysql("-e \"drop database if exists redirect_test\"")
mysql("-e \"create database redirect_test\"")

mysql("-e \"drop database if exists redirect_backup\"")
mysql("-e \"create database redirect_backup\"")
mysql("redirect_backup < /home/redirect/redirect.backup")
