#!/usr/bin/env python
import ConfigParser
import os
from subprocess import check_output

config = ConfigParser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), '../redirect/config.cfg'))

print check_output("mysql -h {0} -u {1} -p{2} -e \"drop database redirect_test\"".format(
    config.get('mysql', 'host'),
    config.get('mysql', 'login'),
    config.get('mysql', 'passwd')), shell=True)

print check_output("mysql -h {0} -u {1} -p{2} -e \"create database redirect_test\"".format(
    config.get('mysql', 'host'),
    config.get('mysql', 'login'),
    config.get('mysql', 'passwd')), shell=True)

print check_output("mysql -h {0} -u {1} -p{2} redirect_test < /home/redirect/redirect.backup".format(
    config.get('mysql', 'host'),
    config.get('mysql', 'login'),
    config.get('mysql', 'passwd')), shell=True)