#!/usr/bin/env python

from os.path import join, dirname
import sys
from ConfigParser import ConfigParser
from database import Runner


if __name__=='__main__':
    if len(sys.argv) < 3:
        sys.exit('Usage: %s <database name> <file name>' % sys.argv[0])

    database = sys.argv[1]
    filename = sys.argv[2]

    config = ConfigParser()
    config.read(join(dirname(__file__), '../redirect/config.cfg'))
    host = config.get('mysql', 'host')
    user = config.get('mysql', 'user')
    passwd = config.get('mysql', 'passwd')

    script_base = join(dirname(__file__), '../db')

    runner = Runner(host, user, passwd)
    runner.restore(database, filename)
