#!/usr/bin/env python

import ConfigParser
import os
from subprocess import check_output
import sys

config = ConfigParser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), '../redirect/config.cfg'))
host = config.get('mysql', 'host')
user = config.get('mysql', 'user')
passwd = config.get('mysql', 'passwd')

if len(sys.argv) < 2:
    sys.exit('Usage: %s database-name' % sys.argv[0])

db = sys.argv[1]

def mysql(query):
    print "running {}".format(query)
    print check_output("mysql -h {0} -u {1} -p{2} {3}".format(host, user, passwd, query), shell=True)

def restore_backup(database_name):
    mysql('-e "drop database if exists {0}"'.format(database_name))
    mysql('-e "create database {0}"'.format(database_name))
    mysql('-e "SET GLOBAL FOREIGN_KEY_CHECKS=0"')
    mysql('{0} < /home/redirect/redirect.backup'.format(database_name))
    mysql('-e "SET GLOBAL FOREIGN_KEY_CHECKS=1"')

restore_backup(db)