#!/usr/bin/env python
import config
import db_helper
from dns import Dns

from boto.route53.record import ResourceRecordSets
import boto.route53


if __name__=='__main__':
    the_config = config.read_redirect_configs()

    main_domain = the_config.get('redirect', 'domain')

    dns = Dns(
        the_config.get('aws', 'access_key_id'),
        the_config.get('aws', 'secret_access_key'),
        the_config.get('aws', 'hosted_zone_id'))

    create_storage = db_helper.get_storage_creator(the_config)

    with create_storage() as storage:
        for domain in storage.domains_iterate():
            print(domain.user_domain)
            if not domain.ip:
                continue
            aws_access_key_id = the_config.get('aws', 'access_key_id')
            aws_secret_access_key = the_config.get('aws', 'secret_access_key')
            hosted_zone_id = the_config.get('aws', 'hosted_zone_id')

            conn = boto.connect_route53(aws_access_key_id, aws_secret_access_key)
            changes = ResourceRecordSets(conn, hosted_zone_id)

            user_domain = '{0}.{1}.'.format(domain.user_domain, main_domain)
            change = changes.add_change('UPSERT', user_domain, 'A')
            change.add_value(domain.ip)

            for service in domain.services:
                change = changes.add_change('UPSERT', service.dns_name(main_domain), 'SRV')
                change.add_value(service.dns_value(main_domain))

            changes.commit()